[package]
name = "deflate"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["oyvindln <oyvindln@users.noreply.github.com>"]
readme = "README.md"
keywords = ["deflate", "zlib", "endoding", "compression"]
repository = "https://github.com/oyvindln/deflate-rs"
homepage = "https://github.com/oyvindln/deflate-rs"
description = """
An in-memory DEFLATE and zlib encoder written in safe rust
"""

[dependencies]
adler32 = "0.3.0"

[dev-dependencies]
#flate2 = { version = "0.2.14", features = ["zlib"], default-features = false }
flate2 = "0.2.14"
#inflate = "*"

[profile.bench]
debug = true

[features]
default = []
unstable = []
