[package]
name = "deflate"
version = "0.7.3"
license = "MIT/Apache-2.0"
authors = ["oyvindln <oyvindln@users.noreply.github.com>"]
readme = "README.md"
keywords = ["flate", "deflate", "zlib", "encoder", "compression"]
repository = "https://github.com/oyvindln/deflate-rs"
homepage = "https://github.com/oyvindln/deflate-rs"
documentation = "https://docs.rs/deflate/"
description = """
A DEFLATE and zlib encoder written in safe rust.
"""
categories = ["compression"]

[dependencies]
adler32 = "0.3.0"
byteorder = "1.0.0"

[dev-dependencies]
flate2 = "0.2.14"
#inflate = "*"
